global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "raft-cluster"
    static_configs:
      - targets:
          - "host.docker.internal:7101"
          - "host.docker.internal:7102"
          - "host.docker.internal:7103"
          - "host.docker.internal:7104"
          - "host.docker.internal:7105"
